import { Photo } from "@/types";

export const PHOTOS: Photo[] = [
  {
    id: "photo-1",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-2",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-3",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-4",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-5",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-6",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-7",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-8",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-9",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-10",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-11",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-12",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-13",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-14",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-15",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-16",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-17",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-18",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
  {
    id: "photo-19",
    src: "/images/photo_2.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 1",
  },
  {
    id: "photo-20",
    src: "/images/photo_3.jpeg",
    width: 4,
    height: 3,
    alt: "Couple photo 2",
  },
];

export const COVER_IMAGES = [
  "/images/photo_1.jpeg",
  "/images/photo_2.jpeg",
  "/images/photo_3.jpeg",
];
